# Generated by Django 2.2.4 on 2023-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230904_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
    ]
